version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: slugger
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: floki
    versions:
    - 0.30.0
  - dependency-name: earmark
    versions:
    - 1.4.13
    - 1.4.14
  - dependency-name: phoenix_live_reload
    versions:
    - 1.3.0
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: phoenix_live_view
    versions:
    - 0.15.4
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
  - dependency-name: phoenix_html
    versions:
    - 2.14.3
